[build]
builder = "nixpacks"
buildCommand = "cd web-server && npm install && cd ../bot && pip install -r requirements.txt"

[deploy]
startCommand = "cd web-server && npm start"

[environment]
PORT = "3000"
NODE_ENV = "production"

# MySQL Database
DATABASE_URL = "mysql://root:QWGJtSPaTMCjODrfySWkTyHyxHzYwEDM@gondola.proxy.rlwy.net:15465/railway"

# Telegram Bot
BOT_TOKEN = "7725874473:AAEEZj4LtuhjcL0lqN9nATOcihJr2uqyhi0"
CREATOR_CHAT_ID = "990561525"
API_SECRET = "secure_verification_system_arkadiy1803_2025"
